### ISSUE TITLE
Implement the Map.isValid() function

### ISSUE THREAD

**Issue by bovard** [bovard/raid#1]
Since maps are auto-generated we need to make sure there exists a valid pathway from the start to the exit before we ask the user to play on the map.

Currently we just say every map is valid.

We need the function to ensure there is a path from start to end.

If you make this a Dijstra's we can also use it to move creeps around at a later point (so create a new file called Dijstras.js that looks like:
(https://upload.wikimedia.org/wikipedia/commons/2/23/Dijkstras_progress_animation.gif)

```
function Dijstra(start, map) {
   this.start = start;
   this.map = map;
   // compute dijstras
}

Dijstra.prototype = {
    canLocationReachStart: function(loc) {
        return true/false if there is a valid path
    },
    getNextSquareToStart: function(loc) {
        returns the next MapLocation to get to the start
    }
}
```

see https://github.com/bovard/raid/blob/master/lib/Map.js#L36

**Comment by bovard** [comment]
![image](https://cloud.githubusercontent.com/assets/997017/13482340/50c79b06-e0a1-11e5-9e5d-3702cbf7d920.png)

**Comment by bovard** [comment]
![dijkstras_progress_animation](https://cloud.githubusercontent.com/assets/997017/13482348/62a5e1a2-e0a1-11e5-95de-7abbd878c243.gif)

**Comment by cdubz** [comment]
Working on a starter implementation of this with the npm module [pathfinding](https://www.npmjs.com/package/pathfinding).

**Comment by cdubz** [comment]
Basic PR is in. What exactly are you thinking for canLocationReachStart() and getNextSquareToStart()? I wasn't sure so I left those concepts out for now.

**Comment by cdubz** [comment]
e72f5e5 closes this issue.
