### ISSUE TITLE
MazeGenerator

### ISSUE THREAD

**Issue by bovard** [bovard/raid#16]
Make a maze level generator

**Comment by bovard** [comment]
should be able to specify the complexity/difficulty of the maze

**Comment by bovard** [comment]
lots of npm packages for this

**Comment by cdubz** [comment]
Yeah that's why I didn't assign myself this one haha. Could the pathfinding library be used for this at all? Don't think so...

**Comment by cdubz** [comment]
:+1: :shipit:
