### ISSUE TITLE
create a hook up a console and add to ui

### ISSUE THREAD

**Issue by bovard** [bovard/raid#19]
create a hook up a console to add to the ui. it should capture player console.log statements as well as provide the round and location they were created at

**Comment by cdubz** [comment]
Hook up is a little tough with React. I could get it in but we'd lose all the nice functionality of the actual console (e.g. expanding objects and what have you). @raph714 will drop a link in his next merge as a simple tip to players to check the real console.

**Comment by raph714** [comment]
I put a link in, however I don't know how to actually make it into a link.. hah. If someone has time they can go back, it's in the first tutorial page, and make it into an actual <a>

**Comment by bovard** [comment]
Will add that to the "improve tutorial ticket"
