### ISSUE TITLE
Add TEAM to unit, unitinfo

### ISSUE THREAD

**Issue by bovard** [bovard/raid#2]
We should add a Team to the Unit, UnitInfo, UnitFactory and Game init.

Create a Team.js with:

```
module.exports = {
    "A": "A",
    "B": "B",
    "NEUTRAL": "NEUTRAL"
}
```

Use Team in all those locations. Player should be Team A, everything else Team B.

Add an API function nearbyEnemies which returns all unit that aren't on your team.

**Comment by cdubz** [comment]
BRO DID I DO IT RITE?
