### ISSUE TITLE
Add overall scoring system

### ISSUE THREAD

**Issue by cdubz** [bovard/raid#23]
Whether or not we are able to work in a highscore system, let's add a scoring mechanism that combines various elements in to an overall score for game play. E.g.:
- 100 points for clearing a level
- 2 points for killing a rat
- 2 points for killing a gnat
- 5 points for killing one of those q things
- etc. etc.

+bonus points for number of rounds left on level clear

Other ideas for things to factor in?

**Comment by bovard** [comment]
- bonus points for hp on level clear

**Comment by cdubz** [comment]
Closed by #27.
