### ISSUE TITLE
Evaluate security of ScoreManager

### ISSUE THREAD

**Issue by cdubz** [bovard/raid#28]
See primarily:
- [`lib/ScoreManager.js`](https://github.com/bovard/raid/blob/master/lib/ScoreManager.js)
- [`lib/ScoreEvent.js`](https://github.com/bovard/raid/blob/master/lib/ScoreEvent.js)
- [`lib/GameRunner.js`](https://github.com/bovard/raid/blob/master/lib/GameRunner.js)

How susceptible is this to basic manipulation by the end user? How can we lock it down better?

I want to get this as tight as we can before we consider any high score server options.

I would assign @bovard to the ticket if I could (:

**Comment by bovard** [comment]
I'll take a look later today

**Comment by bovard** [comment]
Looks good, I think
