### ISSUE TITLE
Feature Idea: add optional 'taunts' string array to unitInfo and 'tauntDelay'

### ISSUE THREAD

**Issue by raph714** [bovard/raid#32]
tauntDelay determines how often the taunt gets sent, and a random one out of the array gets picked to send to the user.

**Comment by bovard** [comment]
Don't know how I feel about this. I suppose adding this would also allow monsters to "fear" the player and make them run away.

The only current supported special action might be to "stun" a player (add to their delay)

**Comment by raph714** [comment]
It wouldn't have a practical effect other than to allow the human to read the taunts. Chris wanted his in game character to be able to do it, and if it's not too hard it might possibly make the game just a little bit richer.

**Comment by cdubz** [comment]
Definitely would like to see this just for fun. Shouldn't be too hard to implement and we can use the console once #19 is closed.

**Comment by bovard** [comment]
won't fix
