### ISSUE TITLE
api to detect if clear line of sight to another location

### ISSUE THREAD

**Issue by raph714** [bovard/raid#45]

**Comment by cdubz** [comment]
Are you getting at having monsters and the player require a clear line of sight to sense? I think this would really be worth doing.

Could [`Pathfinder`](https://github.com/bovard/raid/blob/master/lib/Utils/Pathfinder.js) be used for this? In [`senseNearbyUnits`](https://github.com/bovard/raid/blob/master/lib/GameController.js#L250), the existing pathfinding function could be used on each potential target. And we could add a function to evaluate the path and determine if it indicates line of sight? I'm not actually sure there is a way to determine that, however. I was playing around with the [visual demo for PathFinding.js](http://qiao.github.io/PathFinding.js/visual/) but couldn't piece together how it would work.

Also, maybe this is just _way_ to expensive and there is some better way to do it?

**Comment by cdubz** [comment]
Ray casting! Not pathfinding. Just had to find the right terminology. [grid2](https://www.npmjs.com/package/grid2) is an existing NPM pakacge to look in to, but it looks like it wouldn't fit in to our existing map structures as well as `pathfinding` does. There may also be general implementations to be found elsewhere.

**Comment by raph714** [comment]
It was just an idea that i wanted to apply to specific monsters. Would be sweet to have but not a priority

On Mar 9, 2016, at 5:47 AM, Chris Wells notifications@github.com wrote:

Ray casting! Not pathfinding. Just had to find the right terminology. grid2 is an existing NPM pakacge to look in to, but it looks like it wouldn't fit in to our existing map structures as well as pathfinding does. There may also be general implementations to be found elsewhere.

**Comment by bovard** [comment]
maybe one day!
