### ISSUE TITLE
return false to 'canHeal()' if the hp are at their max.

### ISSUE THREAD

**Issue by raph714** [bovard/raid#47]

**Comment by cdubz** [comment]
I would leave this up to the player. One certainly _can_ take the heal action even if at max HP, it just won't add any HP (: We don't even check the target's `canBeHealed` property in [`canHeal`](https://github.com/bovard/raid/blob/master/lib/GameController.js#L86). That is something I could maybe see adding, but not so much the max HP check. Thoughts?

**Comment by bovard** [comment]
won't fix
