### ISSUE TITLE
Make pathfinding available to the player?

### ISSUE THREAD

**Issue by raph714** [bovard/raid#48]
This is already really challenging to figure out how to deal with the enemies, let alone how to figure out how to navigate around the level. I'm almost 100 lines in on my character and I can get past the first two levels if the cave level doesn't have any tough areas to navigate through. I think it would be more fun and approachable if the player didn't have to worry about pathfinding if all they are doing is heading for the exit. They will still have to do some manual dickery to deal with the monsters, and since there are so many monsters and levels, it would be nice for the player to get a good taste of what they can explore before getting pwned all the time at the higher levels.

**Comment by cdubz** [comment]
I think it would be better to deal with this as part of the balancing process. E.g. earlier levels should have very simple navigation and increasingly difficult creeps while the later levels add more and more complex terrain to deal with in addition to the creeps. Writing one's own path finding should be part of the challenge here. @bovard? @Jerorfigan?

**Comment by bovard** [comment]
Yeah I agree. The first 10 levels or so should be very easy without decent pathfinding. Then things will get progressively harder

**Comment by bovard** [comment]
won't fix
