### ISSUE TITLE
Check NPM dependencies

### ISSUE THREAD

**Issue by cdubz** [bovard/raid#69]
See:
- https://medium.com/@azerbike/i-ve-just-liberated-my-modules-9045c06be67c#.rvut5ydgp
- https://gist.githubusercontent.com/azer/db27417ee84b5f34a6ea/raw/50ab7ef26dbde2d4ea52318a3590af78b2a21162/gistfile1.txt
- http://www.drinchev.com/blog/alert-npm-modules-hijacked/

We should be weary of anything in that list that we depend on. None of our direct dependencies are included, but the full dependency tree needs to be checked.

**Comment by bovard** [comment]
the worst! :(  anyone make an npm package that checks all your npm packages for these yet?

**Comment by cdubz** [comment]
Here is an alpha-sorted and uniqued list of **all** node modules used in our project (arranged from `npm ls`):
- amdefine@1.0.0
- ansi-regex@2.0.0
- ansi-styles@2.2.0
- asap@2.0.3
- babel-code-frame@6.6.5
- babel-core@6.6.5
- babel-generator@6.6.5
- babel-helper-builder-react-jsx@6.6.5
- babel-helpers@6.6.0
- babel-messages@6.6.5
- babel-plugin-syntax-flow@6.5.0
- babel-plugin-syntax-jsx@6.5.0
- babel-plugin-transform-flow-strip-types@6.6.5
- babel-plugin-transform-react-display-name@6.5.0
- babel-plugin-transform-react-jsx-source@6.5.0
- babel-plugin-transform-react-jsx@6.6.5
- babel-preset-react@6.5.0
- babel-register@6.6.5
- babel-runtime@5.8.35
- babel-template@6.6.5
- babel-traverse@6.6.5
- babel-types@6.6.5
- babelify@7.2.0
- babylon@6.6.5
- balanced-match@0.3.0
- base62@0.1.1
- brace-expansion@1.1.3
- brace@0.7.0
- chalk@1.1.1
- classnames@2.2.3
- clone@1.0.2
- color-convert@1.0.0
- commonmark-react-renderer@4.1.2
- commonmark@0.24.0
- concat-map@0.0.1
- convert-source-map@1.2.0
- core-js@1.2.6
- core-js@2.1.3
- debug@2.2.0
- detect-indent@3.0.1
- dom-helpers@2.4.0
- entities@1.1.1
- envify@3.4.0
- escape-string-regexp@1.0.5
- esprima-fb@13001.1001.0-dev-harmony-fb
- esutils@2.0.2
- fbjs@0.6.1
- generate-maze-by-clustering@0.0.4
- get-stdin@4.0.1
- globals@8.18.0
- has-ansi@2.0.0
- heap@0.2.5
- home-or-tmp@1.0.0
- in-publish@2.0.0
- invariant@2.2.0
- is-finite@1.0.1
- is-integer@1.0.6
- js-tokens@1.0.2
- json5@0.4.0
- jstransform@10.1.0
- keycode@2.1.1
- **left-pad@0.0.3**
- line-numbers@0.2.0
- lodash-compat@3.10.2
- lodash.assign@4.0.6
- lodash.isplainobject@4.0.3
- lodash.keys@4.0.5
- lodash.rest@4.0.1
- lodash@3.10.1
- loose-envify@1.1.0
- mdurl@1.0.1
- minimatch@2.0.10
- minimist@0.0.8
- minimist@1.2.0
- mkdirp@0.5.1
- ms@0.7.1
- number-is-nan@1.0.0
- object-assign@4.0.1
- os-tmpdir@1.0.1
- path-exists@1.0.0
- path-is-absolute@1.0.0
- pathfinding@0.4.17
- private@0.1.6
- promise@7.1.1
- react-ace@3.1.0
- react-bootstrap@0.27.3
- react-dom@0.14.7
- react-markdown@2.1.0
- react-overlays@0.5.4
- react-prop-types@0.2.2
- react-prop-types@0.3.0
- react@0.14.7
- repeating@1.1.3
- shebang-regex@1.0.0
- slash@1.0.0
- source-map-support@0.2.10
- source-map@0.1.31
- source-map@0.1.32
- source-map@0.5.3
- string.prototype.repeat@0.2.0
- strip-ansi@3.0.1
- supports-color@2.0.0
- through@2.3.8
- to-fast-properties@1.0.1
- trim-right@1.0.1
- ua-parser-js@0.7.10
- uncontrollable@3.2.1
- user-home@1.1.1
- w3c-blob@0.0.1
- warning@2.1.0
- whatwg-fetch@0.9.0
- xss-filters@1.2.6

The only collision is the most notorious case, `left-pad@0.0.3`, which is ultimately a dependency of both `babel-preset-react` and `babelify` and [has been (in)famously restored](https://twitter.com/seldo/status/712414400808755200) --

```
cdubz@professor-farnsworth ~/WebstormProjects/raid (master=) $ npm ls left-pad
raid@0.0.1 /home/cdubz/WebstormProjects/raid
├─┬ babel-preset-react@6.5.0
│ └─┬ babel-plugin-transform-react-jsx@6.6.5
│   └─┬ babel-helper-builder-react-jsx@6.6.5
│     └─┬ babel-types@6.6.5
│       └─┬ babel-traverse@6.6.5
│         └─┬ babel-code-frame@6.6.5
│           └─┬ line-numbers@0.2.0
│             └── left-pad@0.0.3 
└─┬ babelify@7.2.0
  └─┬ babel-core@6.6.5
    └─┬ babel-code-frame@6.6.5
      └─┬ line-numbers@0.2.0
        └── left-pad@0.0.3 
```

**Comment by cdubz** [comment]
Interesting side note - I just blasted and reinstall my npm modules and it appears that `babel-preset-react` and `babelify` have eliminated the `line-numbers` dependency that included `left-pad`. That was quick.
