### ISSUE TITLE
Feature Idea: Visual code stepping

### ISSUE THREAD

**Issue by cdubz** [bovard/raid#8]
I'm not sure if this is even vaguely feasible, but an interesting idea I had earlier - would it be possible to also provide a visual code stepping tool in the UI? E.g., for each round, a player could use the AceEditor component that is displaying their code to step through each individual line and see the status of any variables they have set, etc. I got this idea from messing around with [The Deadlock Empire](https://deadlockempire.github.io/#menu), which is obviously a much simpler system but illustrates what I am thinking in a way.

As a player, this would be really useful for tweaking the AI especially down the line as it becomes more complicated. This is something I struggled with in Battlecode (though the tools to code-step in that sense probably do exist, just beyond me).

Thoughts? Possible?

**Comment by bovard** [comment]
Won't fix. But would be cool one day
